export component WeatherIcon inherits Image {
    in property <int> code: -1;
    in property <bool> day: false;
    source:
 code == 00? ( day? @image-url("../pict/svg_png/wmo_icon_00d.png") :  @image-url("../pict/svg_png/wmo_icon_00n.png")) :
 code == 01? ( day? @image-url("../pict/svg_png/wmo_icon_01d.png") :  @image-url("../pict/svg_png/wmo_icon_01n.png")) :
 code == 02? ( day? @image-url("../pict/svg_png/wmo_icon_02d.png") :  @image-url("../pict/svg_png/wmo_icon_02n.png")) :
 code == 03? ( day? @image-url("../pict/svg_png/wmo_icon_03d.png") :  @image-url("../pict/svg_png/wmo_icon_03n.png")) :
 code == 45? ( day? @image-url("../pict/svg_png/wmo_icon_45d.png") :  @image-url("../pict/svg_png/wmo_icon_45n.png")) :
 code == 48? ( day? @image-url("../pict/svg_png/wmo_icon_45d.png") :  @image-url("../pict/svg_png/wmo_icon_45n.png")) :
 code == 51? ( day? @image-url("../pict/svg_png/wmo_icon_53d.png") :  @image-url("../pict/svg_png/wmo_icon_53n.png")) :
 code == 53? ( day? @image-url("../pict/svg_png/wmo_icon_53d.png") :  @image-url("../pict/svg_png/wmo_icon_53n.png")) :
 code == 55? ( day? @image-url("../pict/svg_png/wmo_icon_53d.png") :  @image-url("../pict/svg_png/wmo_icon_53n.png")) :
 code == 56? ( day? @image-url("../pict/svg_png/wmo_icon_57d.png") :  @image-url("../pict/svg_png/wmo_icon_57n.png")) :
 code == 57? ( day? @image-url("../pict/svg_png/wmo_icon_57d.png") :  @image-url("../pict/svg_png/wmo_icon_57n.png")) :
 code == 61? ( day? @image-url("../pict/svg_png/wmo_icon_61d.png") :  @image-url("../pict/svg_png/wmo_icon_61n.png")) :
 code == 63? ( day? @image-url("../pict/svg_png/wmo_icon_63d.png") :  @image-url("../pict/svg_png/wmo_icon_63n.png")) :
 code == 65? ( day? @image-url("../pict/svg_png/wmo_icon_65d.png") :  @image-url("../pict/svg_png/wmo_icon_65n.png")) :
 code == 66? ( day? @image-url("../pict/svg_png/wmo_icon_66d.png") :  @image-url("../pict/svg_png/wmo_icon_66n.png")) :
 code == 67? ( day? @image-url("../pict/svg_png/wmo_icon_67d.png") :  @image-url("../pict/svg_png/wmo_icon_67n.png")) :
 code == 71? ( day? @image-url("../pict/svg_png/wmo_icon_71d.png") :  @image-url("../pict/svg_png/wmo_icon_71n.png")) :
 code == 73? ( day? @image-url("../pict/svg_png/wmo_icon_73d.png") :  @image-url("../pict/svg_png/wmo_icon_73n.png")) :
 code == 75? ( day? @image-url("../pict/svg_png/wmo_icon_75d.png") :  @image-url("../pict/svg_png/wmo_icon_75n.png")) :
 code == 77? ( day? @image-url("../pict/svg_png/wmo_icon_75d.png") :  @image-url("../pict/svg_png/wmo_icon_75n.png")) :
 code == 80? ( day? @image-url("../pict/svg_png/wmo_icon_80d.png") :  @image-url("../pict/svg_png/wmo_icon_80n.png")) :
 code == 81? ( day? @image-url("../pict/svg_png/wmo_icon_81d.png") :  @image-url("../pict/svg_png/wmo_icon_81n.png")) :
 code == 82? ( day? @image-url("../pict/svg_png/wmo_icon_81d.png") :  @image-url("../pict/svg_png/wmo_icon_81n.png")) :
 code == 84? ( day? @image-url("../pict/svg_png/wmo_icon_84d.png") :  @image-url("../pict/svg_png/wmo_icon_84n.png")) :
 code == 85? ( day? @image-url("../pict/svg_png/wmo_icon_85d.png") :  @image-url("../pict/svg_png/wmo_icon_85n.png")) :
 code == 86? ( day? @image-url("../pict/svg_png/wmo_icon_86d.png") :  @image-url("../pict/svg_png/wmo_icon_86n.png")) :
 code == 95? ( day? @image-url("../pict/svg_png/wmo_icon_95d.png") :  @image-url("../pict/svg_png/wmo_icon_95n.png")) :
 code == 96? ( day? @image-url("../pict/svg_png/wmo_icon_96d.png") :  @image-url("../pict/svg_png/wmo_icon_96n.png")) :
 code == 99? ( day? @image-url("../pict/svg_png/wmo_icon_96d.png") :  @image-url("../pict/svg_png/wmo_icon_96n.png")) :
 @image-url("../pict/wifi-wait.png");

}
