export global ChartSupport {
    pure callback renderChart(
    	w: int, h: int,
    	data: [float], min: float, max: float,
		lineColor: color, gridColor: color,
	  	gridRowNumber: int, autoGridRowNumber: int, gridColNumber: int) -> image;
    pure callback calcLimits(data: [float]) -> [float];
}

export component Chart inherits Rectangle {
    in property <[float]> data;
    in property <color> lineColor: white;
    in property <color> gridColor: self.lineColor.with-alpha(0.5);
    in property <int> gridRows: -1;
    in property <int> gridCols: 5;
    out property <float> minY;
    out property <float> maxY;
    private property <int> autoGridRows;

    changed data => {
        let verticalBounds = ChartSupport.calcLimits(data);
        minY = verticalBounds[0];
        maxY = verticalBounds[1];
        autoGridRows = verticalBounds[2];
    }
    //to be chart area
    Image {
        x: 0px;
        y: 0px;
        width: parent.width;
        height: parent.height;
        source: ChartSupport.renderChart(parent.width / 1px, parent.height / 1px, data, minY, maxY, lineColor, gridColor, gridRows, autoGridRows, gridCols);
    }

    Text {
        x: 1px;
        y: 0px;
        text: maxY.to-fixed(0);
        color: gridColor;
        font-size: 12px;
    }

    Text {
        x: 1px;
        y: parent.height - self.preferred-height;
        text: minY.to-fixed(0);
        color: gridColor;
        font-size: 12px;
    }
}
