export component DataWidget inherits Rectangle {
    in property <string> name;
    in property <color> borderColor: #0000FF;
    in property <bool> valid: true;
    width: inner.width;
    height: inner.height;
    inner := Rectangle {
        border-color: borderColor;
        border-width: 3px;
        border-radius: 12px;
        background: #FFFFD0;
        width: max(layout.preferred-width + 5px, label.preferred-width + 15px);
        height: layout.preferred-height + 5px;
        label := Rectangle {
            x: 12px;
            y: -10px;
            background: valid ? parent.background : red;
            width: header.preferred-width + 5px;
            height: header.preferred-height + 5px;
            header := Text {
                x: 4px;
                color: borderColor;
                horizontal-alignment: left;
                text: name;
                font-size: 18px;
            }
        }

        layout := VerticalLayout {
            alignment: start;
            padding-bottom: 0px;
            padding-top: 20px;
            padding-left: 15px;
            padding-right: 8px;
            @children
        }
    }
}
