import "NotoSans-Bold.ttf";
import { HorizontalBox } from "std-widgets.slint";
import { DataWidget } from "./data-widget.slint";
import { WeatherIcon } from "./weather-icon.slint";
import { Chart, ChartSupport } from "./chart.slint";
export { ChartSupport }
export enum FoxConditionEnum { cloudy, foggy,good, rainy, snowy, sunny, windy, net_fail }

export struct RuuviData { tempC: float, atmPHgmm: float, relHumidity: float, connFail: bool, battV: float}


export struct OpenMeteoData {
    tempC: float,
    tempFeelsC: float,
    windSpeed: float,
    windGusts: float,
    windDir: string,
    condition: FoxConditionEnum,
    connFail: bool
}

export struct AdaIoData { value: float, connFail: bool}

export struct LocalData { tempC: float, relHumidity: float, tempHistory: [float]}

export component WeatherStation inherits Window {
    in property <int> weather-code: 0;
    in property <bool> day: true;
    in property <LocalData> indoor-data: { relHumidity:0.0001, tempC:-10.00001 };
    in property <AdaIoData> adafruit-data: { value: 333.33455453, connFail: true };
    in property <RuuviData> roovi-data: { relHumidity: 0.0001, tempC: 0.0001, atmPHgmm: 0.0001, battV: 2.7, connFail: true };
    in property <[float]> chart-history;
    in property <OpenMeteoData> meteo-data: {
        tempC: -15.6777,
        tempFeelsC: -18.788878,
        windSpeed: 5.47474,
        windGusts: 7.211,
        windDir: "NW",
        connFail: true
    };
    private property <physical-length> main-font-size: 18px;
    private property <physical-length> reg-widget-width:73px;
    default-font-weight: 1000;

    width: 800px;
    height: 480px;
    background: white;
    WeatherIcon {
        x: 700px;
        y: 20px;
        day: day;
        code: weather-code;
    }

    DataWidget {
        name: "AdaIO";
        valid: !adafruit-data.connFail;
        x: 30px;
        y: 357px;
        width: 185px;
        HorizontalLayout {
            x: 4px;
            width: 170px;
            alignment: start;
            Text {
                text: "CO";
                color: black;
                font-size: main-font-size;
            }

            Text {
                y: 10px;
                color: black;
                font-size: main-font-size - 2px;
                text: "2";
            }

            Text {
                text: ": \{ adafruit-data.value.to-fixed(0)} ppm";
                color: black;
                font-size: main-font-size;
            }
        }
    }

    DataWidget {
        name: "Ruuvi";
        x: 320px;
        y: 20px;
        valid: !roovi-data.connFail;
        GridLayout {
            width: 200px;
            spacing-horizontal: 8px;
            Row {
                HorizontalLayout {
                    alignment: start;
                    Text {
                        color: black;
                        font-size: main-font-size;
                        text: "T: \{roovi-data.tempC.to-fixed(1)}";
                    }

                    Text {
                        color: black;
                        font-size: 8px;
                        text: "O";
                    }

                    Text {
                        color: black;
                        font-size: main-font-size;
                        text: "C";
                    }
                }

                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "H: \{roovi-data.relHumidity.to-fixed(0)}%";
                }
            }

            Row {
                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "P: \{roovi-data.atmPHgmm.to-fixed(0)} mmHg";
                }

                Text {
                    color: roovi-data.battV > 2.7 ? black : roovi-data.battV > 2.5 ? yellow : darkred;
                    font-size: main-font-size;
                    text: "Bat: \{roovi-data.battV.to-fixed(1)}V";
                }
            }
        }
    }

    DataWidget {
        name: "City";
        x: 320px;
        y: 120px;
        valid: !meteo-data.connFail;
        HorizontalLayout {
            width: 133px;
            alignment: start;
            Text {
                color: black;
                font-size: main-font-size;
                text: "T: \{meteo-data.tempC.to-fixed(1)} (\{meteo-data.tempFeelsC.to-fixed(1)} )";
            }

            Text {
                color: black;
                font-size: 8px;
                text: "O";
            }

            Text {
                color: black;
                font-size: main-font-size;
                text: "C";
            }
        }

        Text {
            color: black;
            font-size: main-font-size;
            text: "Wind: \{meteo-data.windDir} \{meteo-data.windSpeed.to-fixed(1)} (\{meteo-data.windGusts.to-fixed(0)}) m/s";
        }
    }

    DataWidget {
        name: "Local";
        x: 20px;
        y: 280px;
        HorizontalLayout {
            width: 200px;
            spacing: 8px;
            HorizontalLayout {
                alignment: start;
                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "T: \{indoor-data.tempC.to-fixed(1)}";
                }

                Text {
                    color: black;
                    font-size: 8px;
                    text: "O";
                }

                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "C";
                }
            }

            Text {
                color: black;
                font-size: main-font-size;
                text: "H: \{indoor-data.relHumidity.to-fixed(0)}%";
            }
        }
    }

    Image {
        x: 0;
        y: 0;
        source: meteo-data.condition == FoxConditionEnum.net-fail ? @image-url("../pict/pencifox/ready/net_fail.png") : meteo-data.condition == FoxConditionEnum.cloudy ? @image-url("../pict/pencifox/ready/cloudy.png") : meteo-data.condition == FoxConditionEnum.foggy ? @image-url("../pict/pencifox/ready/foggy.png") : meteo-data.condition == FoxConditionEnum.good ? @image-url("../pict/pencifox/ready/good.png") : meteo-data.condition == FoxConditionEnum.rainy ? @image-url("../pict/pencifox/ready/rainy.png") : meteo-data.condition == FoxConditionEnum.snowy ? @image-url("../pict/pencifox/ready/snowy.png") : meteo-data.condition == FoxConditionEnum.sunny ? @image-url("../pict/pencifox/ready/sunny.png") : @image-url("../pict/pencifox/ready/windy.png");
    }

    Text {
        x: 300px;
        y: 260px;
        font-size: 18px;
//        font-family: "Roboto";
        text: "Carbone dioxide, ppm, 48hrs";
    }

    Chart {
        x: 300px;
        y: 280px;
        width: parent.width - self.x;
        gridColor: white;
        lineColor: yellow;
        height: 200px;
        background: #0000FF;
        data: chart-history;
    }

    Rectangle {
        x: 0;
        width: parent.width;
        y: 250px;
        height: 2px;
        background: black;
    }
}
