import "font/NotoSans-Bold.ttf";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { DataWidget } from "./data-widget.slint";
import { WeatherIcon } from "./weather-icon.slint";
import { Chart, ChartSupport } from "./chart.slint";
import { ChargeIndicator } from "./charge-indicator.slint";
export { ChartSupport }
export enum FoxConditionEnum { cloudy, foggy, good, drizzly, rainy, snowy, sunny, windy, windy_rainy, net_fail }

export struct RuuviData { tempC: float, atmPHgmm: float, relHumidity: float, connFail: bool, battV: float}

export struct OpenMeteoData {
    tempC: float,
    tempFeelsC: float,
    windSpeed: float,
    windGusts: float,
    windDir: string,
    condition: FoxConditionEnum,
    connFail: bool
}

export struct AdaIoData { value: float, humidity: float, temperature: float, connFail: bool}

export struct LocalData { tempC: float, relHumidity: float, tempHistory: [float]}

export component WeatherStation inherits Window {
	default-font-family: "Noto Sans";
	default-font-weight: 1000;
    in property <int> weather-code: 0;

    in property <bool> day: true;

    in property <LocalData> indoor-data: { relHumidity:0.0001, tempC:-10.00001 };
    in property <AdaIoData> adafruit-data: { value: 333.33455453, humidity: 50.0, temperature: 22.0, connFail: true };
    in property <RuuviData> ruuvi-data: { relHumidity: 0.0001, tempC: 0.0001, atmPHgmm: 0.0001, battV: 2.7, connFail: true };
    in property <[float]> co2-history;
    in property <[float]> pressure-history;
    in property <OpenMeteoData> meteo-data: {
        tempC: -15.6777,
        tempFeelsC: -18.788878,
        windSpeed: 5.47474,
        windGusts: 7.211,
        windDir: "NW",
        connFail: true
    };
    in property <bool> charging;
    in property <percent> charge;
    in property <string> last-update;
    private property <physical-length> main-font-size: 18px;
    pressure-history: [0, 1];
    private property <physical-length> reg-widget-width:73px;
    private property <float> hourly-p-change: 2.0 * (pressure-history[(pressure-history.length - 1)] - pressure-history[(pressure-history.length - 2)]);

    width: 800px;
    height: 480px;
    background: white;
    WeatherIcon {
        x: 700px;
        y: 20px;
        day: day;
        code: weather-code;
    }

    DataWidget {
        name: "Bedroom";
        valid: !adafruit-data.connFail;
        x: 30px;
        y: 350px;
        width: 185px;
        VerticalLayout {
            spacing: 2px;

            HorizontalLayout {
                alignment: start;
                Text {
                    text: "T: \{adafruit-data.temperature.to-fixed(1)}";
                    color: black;
                    font-size: main-font-size;
                }

                Text {
                    color: black;
                    font-size: 8px;
                    text: "O";
                }

                Text {
                    text: "C  H: \{adafruit-data.humidity.to-fixed(0)}%";
                    color: black;
                    font-size: main-font-size;
                }
            }
        }
    }

    DataWidget {
        name: "Ruuvi";
        x: 320px;
        y: 20px;
        valid: !ruuvi-data.connFail;
        GridLayout {
            width: 200px;
            spacing-horizontal: 8px;
            Row {
                HorizontalLayout {
                    alignment: start;
                    Text {
                        color: black;
                        font-size: main-font-size;
                        text: "T: \{ruuvi-data.tempC.to-fixed(1)}";
                    }

                    Text {
                        color: black;
                        font-size: 8px;
                        text: "O";
                    }

                    Text {
                        color: black;
                        font-size: main-font-size;
                        text: "C";
                    }
                }

                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "H: \{ruuvi-data.relHumidity.to-fixed(0)}%";
                }
            }

            Row {

                Text {
                    color: ruuvi-data.battV > 2.7 ? black : ruuvi-data.battV > 2.5 ? yellow : darkred;
                    font-size: main-font-size;
                    text: "Bat: \{ruuvi-data.battV.to-fixed(1)}V";
                }
            }
        }
    }

    DataWidget {
        name: "City";
        x: 320px;
        y: 120px;
        valid: !meteo-data.connFail;
        HorizontalLayout {
            width: 133px;
            alignment: start;
            Text {
                color: black;
                font-size: main-font-size;
                text: "T: \{meteo-data.tempC.to-fixed(1)} (\{meteo-data.tempFeelsC.to-fixed(1)} )";
            }

            Text {
                color: black;
                font-size: 8px;
                text: "O";
            }

            Text {
                color: black;
                font-size: main-font-size;
                text: "C";
            }
        }

        Text {
            color: black;
            font-size: main-font-size;
            text: "Wind: \{meteo-data.windDir} \{meteo-data.windSpeed.to-fixed(1)} (\{meteo-data.windGusts.to-fixed(0)}) m/s";
        }
    }

    DataWidget {
        name: "Local";
        x: 20px;
        y: 280px;
        HorizontalLayout {
            width: 200px;
            spacing: 8px;
            HorizontalLayout {
                alignment: start;
                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "T: \{indoor-data.tempC.to-fixed(1)}";
                }

                Text {
                    color: black;
                    font-size: 8px;
                    text: "O";
                }

                Text {
                    color: black;
                    font-size: main-font-size;
                    text: "C";
                }
            }

            Text {
                color: black;
                font-size: main-font-size;
                text: "H: \{indoor-data.relHumidity.to-fixed(0)}%";
            }
        }
    }

    Image {
        x: 0;
        y: 0;
        source: meteo-data.condition == FoxConditionEnum.net-fail ? @image-url("../pict/pencifox/ready/net_fail.png")
        : meteo-data.condition == FoxConditionEnum.cloudy ? @image-url("../pict/pencifox/ready/cloudy.png")
        : meteo-data.condition == FoxConditionEnum.foggy ? @image-url("../pict/pencifox/ready/foggy.png")
        : meteo-data.condition == FoxConditionEnum.good ? @image-url("../pict/pencifox/ready/good.png")
        : meteo-data.condition == FoxConditionEnum.rainy ? @image-url("../pict/pencifox/ready/rainy.png")
        : meteo-data.condition == FoxConditionEnum.windy_rainy ? @image-url("../pict/pencifox/ready/windy-rainy.png")
        : meteo-data.condition == FoxConditionEnum.drizzly ? @image-url("../pict/pencifox/ready/drizzly.png")
        : meteo-data.condition == FoxConditionEnum.snowy ? @image-url("../pict/pencifox/ready/snowy.png")
        : meteo-data.condition == FoxConditionEnum.sunny ? @image-url("../pict/pencifox/ready/sunny.png")
        : @image-url("../pict/pencifox/ready/windy.png");
    }

    Rectangle { // Splitter
        x: 0;
        width: parent.width;
        height: 2px;
        y: 250px;
        background: black;
    }

    VerticalBox { //P
        x: 320px;
        y: 260px;
        width: 250px;
        height: parent.height - self.y;
        spacing: 0;
        padding: 0;
        Text {
            font-size: 18px;
            text: "P, mmHg (48hrs)";
            color: #0000FF;
            width: parent.width - self.x;
        }

        Rectangle {
            width: 100%;
            Text {
                y: 0;
                height: parent.height;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "\{ruuvi-data.atmPHgmm.to-fixed(0)}";
                font-size: 60px;
                opacity: 0.6;
                color: blue;
            }

            Image {
                source:
                hourly-p-change < -2 ? @image-url("../pict/pressure_icon_q_down.png")
                : hourly-p-change < -1 ? @image-url("../pict/pressure_icon_down.png")
                : hourly-p-change > 2 ? @image-url("../pict/pressure_icon_q_up.png")
                : @image-url("../pict/pressure_icon_up.png");
                visible: (-1 > hourly-p-change) || (1 < hourly-p-change) ;
                horizontal-alignment: right;
                x: 0;
                opacity: 80%;
            }
            Chart {
                y: 0;
                width: 100%;
                height: 100%;
                gridCols: 6;
                lineColor: black;
                gridColor: black;
                data: pressure-history;
            }

        }
    }

    VerticalBox { //CO2
        x: 580px;
        y: 260px;
        width: parent.width - self.x;
        height: 220px;
        padding: 0;
        spacing: 0;
        private property <length> title-font-size: 18px;
        HorizontalLayout {
            spacing: 0;
            alignment: start;
            Text {
                font-size: title-font-size;
                text: "CO";
                color: black;
            }

            Text {
                font-size: title-font-size * 70%;
                vertical-alignment: bottom;
                text: "2";
            }

            Text {
                font-size: title-font-size;
                text: ", ppm, 48hrs";
            }
        }

        Rectangle {
            height: 200px;
            width: parent.width;
            Text {
                y: 0;
                height: parent.height;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "\{adafruit-data.value.to-fixed(0)}";
                font-size: 60px;
                opacity: 0.6;
                color: adafruit-data.value > 1500 ? red
                : adafruit-data.value > 1200 ? brown : #00A000;
            }
            Chart {
                gridColor: #00FF00;
                lineColor: #00FF00;
                data: co2-history;
            }
        }
    }

    HorizontalLayout {
        x: 3px;
        y: parent.height - self.height - 3px;
        height: 20px;

        ChargeIndicator {
            charging: charging;
            charge: charge;
            width: 50px;
            height: parent.height;
        }

        Text {
            text: last-update;
            vertical-alignment: center;
            height: parent.height;
            font-size: parent.height * 70%;
        }
    }
}
