export component WeatherIcon inherits Image {
    in property <int> code: -1;
    in property <bool> day: false;
    source:
 code == 00? ( day? @image-url("../pict/svg_png/clearsky_day.png") :  @image-url("../pict/svg_png/clearsky_night.png")) :
 code == 01? ( day? @image-url("../pict/svg_png/fair_day.png") :  @image-url("../pict/svg_png/fair_night.png")) :
 code == 02? ( day? @image-url("../pict/svg_png/partlycloudy_day.png") :  @image-url("../pict/svg_png/partlycloudy_night.png")) :
 code == 03? @image-url("../pict/svg_png/cloudy.png") :
 code == 45? @image-url("../pict/svg_png/fog.png") :
 code == 48? @image-url("../pict/svg_png/fog.png") :
 code == 51? ( day? @image-url("../pict/svg_png/lightrainshowers_day.png") :  @image-url("../pict/svg_png/lightrainshowers_night.png")) :
 code == 53? ( day? @image-url("../pict/svg_png/rainshowers_day.png") :  @image-url("../pict/svg_png/rainshowers_night.png")) :
 code == 55? ( day? @image-url("../pict/svg_png/heavyrainshowers_day.png") :  @image-url("../pict/svg_png/heavyrainshowers_night.png")) :
 code == 56? ( day? @image-url("../pict/svg_png/lightsleetshowers_day.png") :  @image-url("../pict/svg_png/lightsleetshowers_night.png")) :
 code == 57? ( day? @image-url("../pict/svg_png/sleetshowers_day.png") :  @image-url("../pict/svg_png/sleetshowers_night.png")) :
 code == 61? ( day? @image-url("../pict/svg_png/lightrainshowers_day.png") :  @image-url("../pict/svg_png/lightrainshowers_night.png")) :
 code == 63? ( day? @image-url("../pict/svg_png/rainshowers_day.png") :  @image-url("../pict/svg_png/rainshowers_night.png")) :
 code == 65? ( day? @image-url("../pict/svg_png/heavyrainshowers_day.png") :  @image-url("../pict/svg_png/heavyrainshowers_night.png")) :
 code == 66? ( day? @image-url("../pict/svg_png/lightsleetshowers_day.png") :  @image-url("../pict/svg_png/lightsleetshowers_night.png")) :
 code == 67? ( day? @image-url("../pict/svg_png/sleetshowers_day.png") :  @image-url("../pict/svg_png/sleetshowers_night.png")) :
 code == 71? ( day? @image-url("../pict/svg_png/lightsnowshowers_day.png") :  @image-url("../pict/svg_png/lightsnowshowers_night.png")) :
 code == 73? ( day? @image-url("../pict/svg_png/snowshowers_day.png") :  @image-url("../pict/svg_png/snowshowers_night.png")) :
 code == 75? ( day? @image-url("../pict/svg_png/heavysnowshowers_day.png") :  @image-url("../pict/svg_png/heavysnowshowers_night.png")) :
 code == 77? ( day? @image-url("../pict/svg_png/heavysnowshowers_day.png") :  @image-url("../pict/svg_png/heavysnowshowers_night.png")) :
 code == 80? ( day? @image-url("../pict/svg_png/lightrainshowers_day.png") :  @image-url("../pict/svg_png/lightrainshowers_night.png")) :
 code == 81? ( day? @image-url("../pict/svg_png/rainshowers_day.png") :  @image-url("../pict/svg_png/rainshowers_night.png")) :
 code == 82? ( day? @image-url("../pict/svg_png/heavyrainshowers_day.png") :  @image-url("../pict/svg_png/heavyrainshowers_night.png")) :
 code == 84? ( day? @image-url("../pict/svg_png/heavysleetshowers_day.png") :  @image-url("../pict/svg_png/heavysleetshowers_night.png")) :
 code == 85? ( day? @image-url("../pict/svg_png/lightsnowshowers_day.png") :  @image-url("../pict/svg_png/lightsnowshowers_night.png")) :
 code == 86? ( day? @image-url("../pict/svg_png/snowshowers_day.png") :  @image-url("../pict/svg_png/snowshowers_night.png")) :
 code == 95? ( day? @image-url("../pict/svg_png/rainshowersandthunder_day.png") :  @image-url("../pict/svg_png/rainshowersandthunder_night.png")) :
 code == 96? ( day? @image-url("../pict/svg_png/lightssleetshowersandthunder_day.png") :  @image-url("../pict/svg_png/lightssleetshowersandthunder_night.png")) :
 code == 99? ( day? @image-url("../pict/svg_png/heavysleetshowersandthunder_day.png") :  @image-url("../pict/svg_png/heavysleetshowersandthunder_night.png")) :
 @image-url("../pict/wifi-wait.png");

}
