import { HorizontalBox, VerticalBox, AboutSlint } from "std-widgets.slint";
import { DataWidget } from "./data-widget.slint";
import { WeatherIcon } from "./weather-icon.slint";
import { Chart, ChartSupport } from "./chart.slint";
import { ChargeIndicator } from "./charge-indicator.slint";
export { ChartSupport }
export enum FoxConditionEnum { cloudy, foggy, good, drizzly, rainy, snowy, sunny, windy, windy_rainy, net_fail }

export struct RuuviData { tempC: float, atmPHgmm: float, relHumidity: float, connFail: bool, battV: float}

export struct OpenMeteoData {
    tempC: float,
    tempFeelsC: float,
    windSpeed: float,
    windGusts: float,
    windDir: string,
    condition: FoxConditionEnum,
    connFail: bool
}

export struct AdaIoData { value: float, humidity: float, temperature: float, connFail: bool}

export struct LocalData { tempC: float, relHumidity: float, tempHistory: [float]}

export component WeatherStation inherits Window {
//	default-font-weight: 800;
	default-font-family: "Verdana";
	default-font-size: 40px;
    in property <int> weather-code: 0;

    in property <bool> day: true;

    in property <LocalData> indoor-data: { relHumidity:0.0001, tempC:-10.00001 };
    in property <AdaIoData> adafruit-data: { value: 333.33455453, humidity: 50.0, temperature: 22.0, connFail: true };
    in property <RuuviData> ruuvi-data: { relHumidity: 0.0001, tempC: 0.0001, atmPHgmm: 0.0001, battV: 2.7, connFail: true };
    in property <[float]> co2-history;
    in property <[float]> pressure-history;
    in property <OpenMeteoData> meteo-data: {
        tempC: -15.6777,
        tempFeelsC: -18.788878,
        windSpeed: 5.47474,
        windGusts: 7.211,
        windDir: "NW",
        connFail: true
    };
    in property <bool> charging;
    in property <percent> charge;
    in property <string> last-update;
    private property <physical-length> main-font-size: 40px;
    pressure-history: [0, 1];
    private property <physical-length> reg-widget-width:73px;
    private property <float> hourly-p-change: 2.0 * (pressure-history[(pressure-history.length - 1)] - pressure-history[(pressure-history.length - 2)]);

    width: 800px;
    height: 480px;
    background: white;
    DataWidget {
        name: "OpenMeteo";
        x: 20px;
        y: 20px;
        valid: !meteo-data.connFail;
        VerticalLayout {
        	width: 390px;
        	alignment: start;
			Text {
				text: "Temp";
				color: black;
				font-italic: false;
			    font-size: main-font-size * 2 / 3;
			}

			HorizontalLayout {
				alignment: start;
				Text {
					color: black;
					font-size: main-font-size;
					text: "\{meteo-data.tempC.to-fixed(1)} (\{meteo-data.tempFeelsC.to-fixed(1)})";
				}

				Text {
					color: black;
					font-size: main-font-size / 2;
					text: "O";
				}

				Text {
					color: black;
					font-size: main-font-size;
					text: "C";
				}
			}
			Text {
				text: "Wind";
				color: black;
				font-size: main-font-size * 2 / 3;
			}

			Text {
				color: black;
				font-size: main-font-size;
				text: "\{meteo-data.windDir} \{meteo-data.windSpeed.to-fixed(1)} (\{meteo-data.windGusts.to-fixed(0)}) m/s";
			}
    	}
    }
	WeatherIcon {
		y:30px;
		x: 350px;
		day: day;
		code: weather-code;
		height: 80px;
	}

    DataWidget {
        name: "Ruuvi";
        x: 260px;
        y: 248px;
        valid: !ruuvi-data.connFail;
			Text {
				text: "Temp";
				color: black;
				font-size: main-font-size * 2 / 3;
			}
			HorizontalLayout {
				width: 150px;
				alignment: start;
				Text {
					text: "\{ruuvi-data.tempC.to-fixed(1)}";
					color: black;
					font-size: main-font-size;
				}

				Text {
					color: black;
					font-size: main-font-size/2;
					text: "O";
				}
				Text {
					text: "C";
					color: black;
					font-size: main-font-size;
				}
			}
    		Rectangle { height: 5px;}
			Text {
				text: "Humidity";
				color: black;
				font-size: main-font-size * 2 / 3;
			}
			Text {
				text: "\{ruuvi-data.relHumidity.to-fixed(0)}%";
				color: black;
				font-size: main-font-size;
			}
			Text {
				color: ruuvi-data.battV > 2.7 ? black : ruuvi-data.battV > 2.5 ? yellow : darkred;
				font-size: main-font-size * 2 / 3;
				text: "Bat: \{ruuvi-data.battV.to-fixed(1)}V";
			}
		}

    Image {
        x: 0;
        y: 217px;
        width: 250px;
        height: 250px;
        z: -1;
        source: meteo-data.condition == FoxConditionEnum.net-fail ? @image-url("../pict/pencifox/ready/net_fail.png")
        : meteo-data.condition == FoxConditionEnum.cloudy ? @image-url("../pict/pencifox/ready/cloudy.png")
        : meteo-data.condition == FoxConditionEnum.foggy ? @image-url("../pict/pencifox/ready/foggy.png")
        : meteo-data.condition == FoxConditionEnum.good ? @image-url("../pict/pencifox/ready/good.png")
        : meteo-data.condition == FoxConditionEnum.rainy ? @image-url("../pict/pencifox/ready/rainy.png")
        : meteo-data.condition == FoxConditionEnum.windy_rainy ? @image-url("../pict/pencifox/ready/windy-rainy.png")
        : meteo-data.condition == FoxConditionEnum.drizzly ? @image-url("../pict/pencifox/ready/drizzly.png")
        : meteo-data.condition == FoxConditionEnum.snowy ? @image-url("../pict/pencifox/ready/snowy.png")
        : meteo-data.condition == FoxConditionEnum.sunny ? @image-url("../pict/pencifox/ready/sunny.png")
        : @image-url("../pict/pencifox/ready/windy.png");
    }
	HorizontalLayout {
		x: 3px;
		y: parent.height - self.height - 3px;
		height: 20px;

		ChargeIndicator {
			charging: charging;
			charge: charge;
			width: 50px;
			height: parent.height;
		}

		Text {
			text: last-update;
			vertical-alignment: center;
			height: parent.height;
			font-size: parent.height * 70%;
		}
	}



// House
/*
    Path {
     x: 450px;
     y:1px;
     width: 350px;
     height: 479px;
     viewbox-height: 100;
     viewbox-width: 100;
     stroke: #880;
     stroke-width: 3px;
     fit:fill;

     MoveTo {x:50;y:0;}
     LineTo {x:100;y:10;}
     LineTo {x:100;y:100;}
     LineTo {x:0;y:100;}
     LineTo {x:0;y:10;}
     LineTo {x:50;y:0;}
     MoveTo {x:0;y:52;}
     LineTo {x:100;y:52;}
    }
*/
	Image {
	  source: @image-url("../pict/house_bg.png");
	  z:-1;
	  y:1px;
	  x: parent.width -self.width;
	}
// 2nd story
	VerticalLayout {
		x:460px;
		alignment: start;
		y:50px;
		Text {
			text: "Temp";
			color: black;
			font-size: main-font-size * 2 / 3;
		}
		HorizontalLayout {
			alignment: start;
			Text {
				text: "\{indoor-data.tempC.to-fixed(1)}";
				color: black;
				font-size: main-font-size;
			}

			Text {
				color: black;
				font-size: main-font-size/2;
				text: "O";
			}
			Text {
				text: "C";
				color: black;
				font-size: main-font-size;
			}
		}
		Rectangle { height: 10px;}
		Text {
			text: "Humidity";
			color: black;
			font-size: main-font-size * 2 / 3;
		}
		Text {
			text: "\{indoor-data.relHumidity.to-fixed(0)}%";
			color: black;
			font-size: main-font-size;
		}
	}


    VerticalBox { //P
        x: 600px;
        y: 45px;
		width: parent.width - self.x - 5px;
        height: 240px - self.y;
        spacing: 0;
        padding: 0;
        Text {
            font-size: 18px;
            text: "P, mmHg (48hrs)";
            color: #0000FF;
            width: parent.width - self.x;
        }

        Rectangle {
            width: 100%;
            Text {
                y: 0;
                height: parent.height;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "\{ruuvi-data.atmPHgmm.to-fixed(0)}";
                font-size: 60px;
                opacity: 0.6;
                color: blue;
            }

            Image {
                source:
                hourly-p-change < -2 ? @image-url("../pict/pressure_icon_q_down.png")
                : hourly-p-change < -1 ? @image-url("../pict/pressure_icon_down.png")
                : hourly-p-change > 2 ? @image-url("../pict/pressure_icon_q_up.png")
                : @image-url("../pict/pressure_icon_up.png");
                visible: (-1 > hourly-p-change) || (1 < hourly-p-change) ;
                horizontal-alignment: right;
                x: 0;
                opacity: 80%;
            }
            Chart {
                y: 0;
                width: 100%;
                height: 100%;
                gridCols: 6;
                lineColor: black;
                gridColor: black;
                data: pressure-history;
            }

        }
    }

    // 1st story
	VerticalLayout {
		x:460px;
		alignment: start;
		y:260px;
		Text {
			text: "Temp";
			color: black;
			font-size: main-font-size * 2 / 3;
		}
		HorizontalLayout {
			alignment: start;
			Text {
				text: "\{adafruit-data.temperature.to-fixed(1)}";
				color: black;
				font-size: main-font-size;
			}

			Text {
				color: black;
				font-size: main-font-size/2;
				text: "O";
			}
			Text {
				text: "C";
				color: black;
				font-size: main-font-size;
			}
		}
		Rectangle { height: 10px;}
		Text {
			text: "Humidity";
			color: black;
			font-size: main-font-size * 2 / 3;
		}
		Text {
			text: "\{adafruit-data.humidity.to-fixed(0)}%";
			color: black;
			font-size: main-font-size;
		}
	}
	VerticalBox { //CO2
		x: 600px;
		y: 250px;
		width: parent.width - self.x - 5px;
		height: 220px;
		padding: 0;
		spacing: 0;
		private property <length> title-font-size: 18px;
		HorizontalLayout {
			spacing: 0;
			alignment: start;
			Text {
				font-size: title-font-size;
				text: "CO";
				color: black;
			}

			Text {
				font-size: title-font-size * 70%;
				vertical-alignment: bottom;
				text: "2";
			}

			Text {
				font-size: title-font-size;
				text: ", ppm, 48hrs";
			}
		}

		Rectangle {
			height: 200px;
			width: parent.width;
			Text {
				y: 0;
				height: parent.height;
				horizontal-alignment: center;
				vertical-alignment: center;
				text: "\{adafruit-data.value.to-fixed(0)}";
				font-size: 60px;
				opacity: 0.6;
				color: adafruit-data.value > 1500 ? red
				: adafruit-data.value > 1200 ? brown : #00A000;
			}
			Chart {
				gridColor: #00FF00;
				lineColor: #00FF00;
				data: co2-history;
			}
		}
	}
}
